# Generated by Django 4.1.4 on 2023-02-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Schools",
            new_name="School",
        ),
    ]
